---
  - name: copy Network Manager conf file
    template:
      src:  /Ziyotech-team4/ansible/templates/NetworkManager.conf.j2
      dest:  /etc/NetworkManager/NetworkManager.conf
    notify:  restart NetworkManager

  - name: configure resolv.conf file
    template:
      src: /Ziyotech-team4/ansible/templates/resolv.conf.j2
      dest: /etc/resolv.conf
    notify: restart network

  - name: start network service
    service:
      name: network
      state: started
