---
- name: configure repo on client server
  hosts: all
  remote_user: root
  become: yes
  
  tasks:
    - name: Install yum-utils package
      yum:
          name: yum-utils
          state: latest
          
    - name: Add CentOS_7_6 repository
      shell: yum-config-manager --add-repo=http://192.168.44.18/repos/CentOS/7/6/
      args:
        creates: /etc/yum.repos.d/centos_7_6.repo 