---
- name: install and configure Apache
  hosts: Centos6_web_servers
  remote_user: root
  become: yes
  
  tasks:
    - name: install latest version of Apache
      yum: name=httpd state=latest
      
    - name: enable Apache on system boot
      service: name=httpd enabled=yes
    
    - name: start httpd service
      service: name=httpd state=started
      
    - name: copy the index.html file
      template: src=/Ziyotech-team4/ansible/files/index.html dest=/var/www/html owner=apache group=apache mode=0644
      
    - name: add hostname to index.html file
      command: sed -i s/Server/{{ ansible_hostname }}/g /var/www/html
      
    - name: restart Apache service
      service: name=httpd state=restarted
      
    - name: install the iptables package
      package: name=iptables state=latest
    
    - name: flush existing firewall rules
      iptables: flush=true
    
    - name: firewall rule - allow port 80/HTTP traffic
      iptables: chain=INPUT destination_port=80 jump=ACCEPT protocol=tcp