---
- hosts: web_servers 
  remote_user: root
  become: yes

  tasks:
  - name: copy html file
    template:
      src: '/var/www/html/index.html'
      dest: '/var/www/html/'
    notify:
    - restart network

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
