---
- name: install initial packages on all servers
  hosts: all
  remote_user: root
  become: yes

  tasks:
  - name: install all initial packages
    yum:
      name: [ 'man', 'sysstat', 'man-pages', 'mlocate', 'vim', 'bind', 'bind-utils' ]
      state: latest
