
---
- name: configure mirror repo over http
  hosts: ftp-server
  remote_user: root
  become: yes

  tasks:
  - name: Allow Web service in Firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true

  - name: install httpd and createrepo package
    yum:
      name: [ 'httpd', 'createrepo', 'rsync' ]
      state: latest

  - name: start httpd service
    service:
      name: httpd
      state: started

  - name: enable httpd service
    service:
      name: httpd
      enabled: yes

  - name: Create repository directory
    file:
      path: /repos/CentOS/7/6/
      state: directory

  - name: Create repomd repository
    command: createrepo /repos/CentOS/7/6/

  - name: Download packages from online repository
    shell: rsync -avz --progress rsync://mirror.umd.edu/centos/7.6.1810/os/x86_64/ /repos/CentOS/7/6/

  - name: Create symbolic link from Apache root directory to repository directory
    command: ln -s /repos/CentOS/7/6 /var/www/html/CentOS/7/6

  - name: Sync repository nightly
    cron:
      name: Updates CentOS 7.6 repository nightly