---
- name: configure mirror repo over http
  hosts: ftp-server
  remote_user: ansible
  become: yes

  tasks:
  - name: install httpd and createrepo package
    yum:
      name: [ 'httpd', 'createrepo', 'rsync' ]
      state: latest

  - name: start httpd service
    service:
      name: httpd
      state: started

  - name: enable httpd service
    service:
      name: httpd
      enabled: yes
      
  - name: Create repo directory
    file:
      path: /var/www/html/repos/centos/7
      state: directory

  - name: configure chrony
    template:
      src: /ansible/templates/chrony.conf.j2
      dest: /etc/chrony.conf
    notify: restart chronyd   

  handlers:
  - name: restart chronyd
    service:  
      name: chronyd
      state: restarted  
