---
- name: configure nagios clients
  hosts: 192.168.44.10
  remote_user: root
  become: yes

  tasks:
  - name: install epel-release repo on clients
    yum:
      name: epel-release
      state: latest

  - name: install nrpe nagios-plugins-all package on clients
    yum:
      name: "'nrpe nagios-plugins-all'"
      state: latest

  - name: Copy configured nrpe.cfg file client servers
    template:
      src: /Ziyotech-team4/ansible/templates/nrpe.cfg.j2
      dest: /etc/nagios/nrpe.cfg

  - name: start nrpe service
    service:
      name: nrpe
      state: started

  - name: enable nrpe service
    service:
      name: nrpe
      enabled: yes
