---
- name: update resolv.conf file  
  hosts: time_servers
  remote_user: root
  become: yes

  tasks:
  - name: configure resolv.conf file
    template:
      src: /ansible/templates/resolv.conf.j2
      dest: /etc/resolv.conf
    notify: restart network

  - name: start network service
    service:
      name: network
      state: started

  handlers:
  - name: restart network
    service:
      name: network
      state: restarted
