---
- name: update resolv.conf file
  hosts: db_servers
  remote_user: root
  become: yes

  tasks:
  - name: copy Network Manager conf file
    template:
      src:  /ansible/ansible/templates/NetworkManager.conf.j2
      dest:  /etc/NetworkManager/NetworkManager.conf
    notify:  restart NetworkManager

  - name: configure resolv.conf file
    template:
      src: /ansible/ansible/templates/resolv.conf.j2
      dest: /etc/resolv.conf
    notify: restart network

  - name: start network service
    service:
      name: network
      state: started

  handlers:
  - name: restart network
    service:
      name: network
      state: restarted
  - name: restart NetworkManager
    service:
      name: NetworkManager
      state: restarted
