---
- name: update kernel to latest
  hosts: 192.168.44.126
  remote_user: root
  become: yes

  tasks:
  - name:   add ELRepo gpg key to the system
    shell: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

  - name:   add new ELRepo repository with rpm command
    shell: rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm

  - name:   install latest kernel version
    shell: yum --enablerepo=elrepo-kernel install kernel-ml

 # - name:   Check all available kernel versions with the awk command below
 #   shell: name: 'awk -F\' '$1=="menuentry " {print i++ " : " $2}' /etc/grub2.cfg

  - name:   set the latest kernel as a default
    shell: grub2-set-default 0

  - name:   generate the grub2 config with gurb2-mkconfig command
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
