---
  - name: install all initial packages
    yum:
      name: [ 'openldap-clients', 'nss-pam-ldapd', 'sssd', 'nfs-utils', 'autofs' ]
      state: latest

  - name: "LDAP Authentication | Enable LDAP PAM modules"
    command: "authconfig --enableldap --enableldapauth --ldapserver=prdx-ldap14.ziyotek4.local --ldapbasedn='dc=ziyotek4,dc=local' --enableldaptls --ldaploadcacert=http://prdx-ldap14/ldap.pem --enablemkhomedir --disableldaptls --update"
    ignore_errors: yes	

  - name: "LDAP Authentication | Adding configuration templates"
    template: 
        src="/ansible/ansible/templates/auto.master.j2"
        dest="/etc/auto.master"

  - name: configure ldap
    template:
      src: /ansible/ansible/templates/auto.home.j2
      dest: /etc/auto.home

  - replace:
      path: /etc/pam.d/password-auth-ac
      regexp: 'pam_sss.so'
      replace: 'pam_ldap.so'
      backup: yes

  - name: start nslcd service
    service:
      name: nslcd
      state: restarted

  - name: start sshd service
    service:
      name: sshd
      state: restarted

  - name: start autofs service
    service:
      name: autofs
      state: started

  - name: enable autofs service
    service:
      name: autofs
      enabled: yes
