---
- name: configure autofs client
  hosts: nfs-clients
  remote_user: root
  become: yes

  tasks:
  - name: copy auto.client.j2
    template:
      src:  /Ziyotech-team4/ansible/templates/auto.client.j2
      dest:  /etc/auto.client

  - name: copy auto.master.j2
    template:
      src: /Ziyotech-team4/ansible/templates/auto.master.j2
      dest: /etc/auto.master
    notify: restart autofs

  
